# Generated by Django 5.2.1 on 2025-05-31 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_businesse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesse',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='businesse',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='businesse',
            name='category',
            field=models.CharField(choices=[('retail', 'Роздрібна торгівля'), ('hospitality', 'Гостинність'), ('technology', 'Технології'), ('finance', 'Фінанси'), ('healthcare', 'Охорона здоров’я'), ('manufacturing', 'Виробництво'), ('construction', 'Будівництво'), ('education', 'Освіта'), ('transportation', 'Транспорт'), ('real_estate', 'Нерухомість'), ('food_and_beverage', 'Харчування та напої'), ('professional_services', 'Професійні послуги'), ('entertainment', 'Розваги'), ('agriculture', 'Сільське господарство'), ('non_profit', 'Некомерційна організація')], default='pending', max_length=21),
        ),
        migrations.AddField(
            model_name='businesse',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesse',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesse',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesse',
            name='site_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesse',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оцінка не може бути меншою за 1'), django.core.validators.MaxValueValidator(5, message='Оцінка не може бути більшою за 5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businesse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'business')},
            },
        ),
    ]
