# Generated by Django 5.2.1 on 2025-05-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_businesse_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='buisnes/')),
                ('businesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businesse')),
            ],
        ),
    ]
