# Generated by Django 5.2.1 on 2025-05-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_buisnessephoto_delete_businessephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesse',
            name='site_page',
        ),
    ]
