# Generated by Django 5.2.1 on 2025-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_businesse_site_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesse',
            name='insta',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
